name: PR Issue Checker Workflow

on:
  pull_request:
    branches:
      - main
    types:
      - opened

jobs:
  check-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        uses: ./.github/workflows/test.yml
      - name: Build
        uses: ./.github/workflows/build.yml
      - name: Deploy
        uses: ./.github/workflows/deploy.yml